name: Deploy to AKS

env:
 resourceGroup: 'class'
 name: 'wasimclass'
 kubenrtesVersion: '1.30'
 
 
 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: azure/login@v2
        with:
           creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    #  - name: Azure CLI Action
     #   uses: Azure/cli@v2.1.0
      #  with:
     #     # Specify the script here
      #    inlineScript: az aks create -g ${{env.resourceGroup}} -n ${{env.name}} --kubernetes-version $kubenrtesVersion --generate-ssh-keys
       
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.resourceGroup }} --name ${{ env.name }}
      - name: Azure Login
        uses: azure/docker-login@v1
        with:
           login-server: demopush.azurecr.io
           username: ${{ secrets.ACR_USERNAME }}
           password: ${{ secrets.ACR_PASSWORD }}

   

      # Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f deploy.yml
